agents:
  PDM4AR_1:
    state:
      x: -9
      y: -9
      psi: 1
    color: 'saddlebrown'
  # PDM4AR_2:
  #   state:
  #     x: -9
  #     y: 9
  #     psi: 1
  #   color: 'saddlebrown'

shared_goals:
  - id: 'goal_1'
    center: [ -7, -9]
    radius: 0.3
  - id: 'goal_2'
    center: [ -7, 9]
    radius: 0.3

# Collection points where goals should be delivered
collection_points:
  # - id: 'collection_1'
  #   center: [ 9, 9 ]
  #   radius: 1.0
  
  - id: 'collection_1'
    center: [ 9, -9 ]
    radius: 1.0
    
static_obstacles:
  - [ [ -7, -2 ], [ -7, 2 ], [ -9, 2 ], [ -9, -2 ] ]

boundary: [ [ -10, -10 ], [ -10, 10 ], [ 10, 10 ], [ 10, -10 ], [ -10, -10 ] ]

seed: 98